# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Firebase GitHub Action
      uses: pizzafox/firebase-action@1.0.7
      env:
        PROJECT_ID: " corona-app-8de93"
        FIREBASE_TOKEN: "1//0hsax3dPiCjy8CgYIARAAGBESNwF-L9IrpDZ1jw82yBog25dvYE-avMP0fuHT-NwRGMK4GciWl5WfJtDPX3mLSyyrCQVDkFPJVsQ"
      with:
        args: deploy
